version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mitori_engine:
    build:
      context: ./mitori_engine
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0  
    depends_on:
      - redis
    volumes:
      - ./mitori_engine:/app

  mitori_backend:
    build:
      context: ./mitori_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./mitori_backend:/app
  trade_daemon:
    build:
      context: ./mitori_backend
    command: python manage.py trade_registery
    depends_on:
      - postgres
      - redis
      - mitori_backend
    env_file:
      - .env

  cancellation_daemon:
    build:
      context: ./mitori_backend
    command: python manage.py settle_cancelled_orders
    depends_on:
      - postgres
      - redis
      - mitori_backend
    env_file:
      - .env
      
volumes:
  postgres_data: