# Generated by Django 6.0.6 on 2026-07-05 18:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrawal'), ('BUY', 'buy'), ('SELL', 'sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('status', models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending'), ('FAILED', 'failed')], max_length=10)),
                ('asset_symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ledger.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=6)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('average_entry_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ledger.portfolio')),
            ],
        ),
    ]
