# Generated by Django 6.0.6 on 2026-07-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='uuid',
            new_name='id',
        ),
    ]
