# Generated by Django 6.0.6 on 2026-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending'), ('FAILED', 'failed')], default='PENDING', max_length=10),
        ),
    ]
