# Generated by Django 6.0.6 on 2026-07-20 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0002_alter_ledgertransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 17, 20, 23, 900008, tzinfo=datetime.timezone.utc)),
        ),
    ]
