# Generated by Django 6.0.6 on 2026-07-20 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0003_portfolio_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
