# Generated by Django 6.0.6 on 2026-07-22 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0005_ledgertransaction_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgertransaction',
            old_name='amount',
            new_name='price_setteled_at',
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='price_locked_by_user',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
