# Generated by Django 6.0.6 on 2026-07-25 07:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0006_rename_amount_ledgertransaction_price_setteled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending'), ('FAILED', 'failed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='CancelledOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrawal'), ('BUY', 'buy'), ('SELL', 'sell')], max_length=10)),
                ('price_locked_by_user', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'completed'), ('PENDING', 'pending'), ('FAILED', 'failed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=10)),
                ('asset_symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ledger.portfolio')),
            ],
        ),
    ]
