# Generated by Django 6.0.6 on 2026-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0007_alter_ledgertransaction_status_cancelledorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='stream_order_id',
            field=models.CharField(default='temp_id', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
