# Generated by Django 6.0.6 on 2026-07-29 09:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0008_ledgertransaction_stream_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorders',
            name='price_locked_by_user',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=60),
        ),
        migrations.AlterField(
            model_name='cancelledorders',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=60),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='price_locked_by_user',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=60),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='price_setteled_at',
            field=models.DecimalField(decimal_places=8, max_digits=60),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=60),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=60),
        ),
        migrations.AlterField(
            model_name='position',
            name='average_entry_price',
            field=models.DecimalField(decimal_places=8, max_digits=60),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=60),
        ),
    ]
