# Generated by Django 6.0.6 on 2026-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ledger', '0009_alter_cancelledorders_price_locked_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledorders',
            name='stream_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
